[wofi]
# Hide search bar
hide_search=true

# Hide scroll bar
hide_scroll=true

# Run with single click
single_click=true

# Show in top right corner
location=3

# Offset
x=-3
y=4

# Size
width=150
height=177

# Use the predefined order ("alphabetical" is misleading)
sort_order=alphabetical

# Additional keybinds
key_down=j
key_up=k
key_submit=l
key_exit=h
