#   ____  _                 _     _
#  / ___|| |_ __ _ _ __ ___| |__ (_)_ __
#  \___ \| __/ _` | '__/ __| '_ \| | '_ \
#   ___) | || (_| | |  \__ \ | | | | |_) |
#  |____/ \__\__,_|_|  |___/_| |_|_| .__/
#                                  |_|

[directory]
truncation_length = 8
