# __   __        _
# \ \ / /_ _ ___(_)
#  \ V / _` |_  / |
#   | | (_| |/ /| |
#   |_|\__,_/___|_|

# Default config:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[mgr]
prepend_keymap = [
    # Instead of opening directories in vim, navigate to them
    # You can still open them in vim by pressing O, Shift+O or Shift+Enter
    { on = "<Enter>", run = "enter", desc = "Enter the child directory" },

    # Operation
    { on = "r", run = "rename", desc = "Rename selected file(s)" },
    { on = "R", run = "rename --cursor=before_ext", desc = "Rename selected file(s) (no extension)" },

    # Goto
    { on = [ "g", "t" ], run = "cd ~/git", desc = "Go into ~/git" },
    { on = [ "g", "f" ], run = "follow", desc = "Follow hovered symlink" },
]
