# __   __        _
# \ \ / /_ _ ___(_)
#  \ V / _` |_  / |
#   | | (_| |/ /| |
#   |_|\__,_/___|_|

# Docs:
# https://yazi-rs.github.io/docs/configuration/overview/

# Default config:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[manager]
ratio = [2, 3, 3]
# sort_sensitive = true
# sort_dir_first = true
# show_hidden = false

[preview]
image_quality = 50
